Matrix is like tow dimentional collection of numbers it is like spreadsheet 
when we are talking about size of matrix we refer number of rows(m) and columns(n)
if m=n it is called square matrix 
if (3,7) we call it rectangular  

In [1]:
import numpy as np 

In [2]:
#create identity matrix I
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [3]:

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
# full creates matrices with given np.full((5,2),7) size and order and number to full 7
np.full((5,2),7)

array([[7, 7],
       [7, 7],
       [7, 7],
       [7, 7],
       [7, 7]])

In [6]:
M=np.array([[1,2,3],[2,3,4],[5,6,7]])
M

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [9]:
#assigment 
#create 3 matrices :2,2 , 2,2,  ,3,2
# compute scalar matrix multiplication 

A=np.matrix([[2,4],[5,4]])
A.shape

(2, 2)

In [10]:
B=np.matrix([[2,6],[3,6]])
B.shape 

(2, 2)

In [11]:
C=np.matrix([[2,4],[5,4],[7,-1]])
C.shape

(3, 2)

In [12]:
#scalar matrix multiplication 
A@B

matrix([[16, 36],
        [22, 54]])

In [13]:
np.dot(A, B)

matrix([[16, 36],
        [22, 54]])

In [16]:
A@C

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [17]:
A+B

matrix([[ 4, 10],
        [ 8, 10]])

In [18]:
B+A

matrix([[ 4, 10],
        [ 8, 10]])

In [19]:
A+C

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 