Symmetric matrices mirrors across th diogonal /a square matrix that remains unaltered when its transpose is calculated. 

A = AT

In [1]:
import numpy as np 

In [4]:
v1=np.array([2,3,-1],ndmin=2)
print(v1)
print(" ")
# in order to get its  transpose v1.T
print(v1.T)

[[ 2  3 -1]]
 
[[ 2]
 [ 3]
 [-1]]


Transpose of matrix 

In [ ]:
M=np.random.randn(3,3)
print(M)

In [9]:
M=np.round(np.random.randn(3,3))
print(M)
print(" ")
print(M.T)

[[-1.  1. -0.]
 [-0.  2.  1.]
 [ 0. -1.  0.]]
 
[[-1. -0.  0.]
 [ 1.  2. -1.]
 [-0.  1.  0.]]


In [ ]:
#assigment 
#what happens if you transpose matrix twice ?
#confirm that the  tranpose works in none square matrices 



In [10]:
A=np.matrix([[2,4],[5,4],[6,7]])
A.shape

(3, 2)

In [11]:
print(A)
print(' ')
print(A.T)

[[2 4]
 [5 4]
 [6 7]]
 
[[2 5 6]
 [4 4 7]]


In [13]:
#it is rotating around itx axis 
A2=A.T

print(A2)
print(' ')
print(A2.T)

[[2 5 6]
 [4 4 7]]
 
[[2 4]
 [5 4]
 [6 7]]


In [14]:
C=np.matrix([[2,4,1,5,6],[5,4,5,6,7]])
C.shape

(2, 5)

In [15]:
print(C)
print(' ')
print(C.T)

[[2 4 1 5 6]
 [5 4 5 6 7]]
 
[[2 5]
 [4 4]
 [1 5]
 [5 6]
 [6 7]]
