Matrix multiplication 

In [1]:
#AB one result while BA another so they are not similar 

MxN  NxK    if their inner dimention match or number of coulms from M1 matches with number of rows M2 then we can multiply them result MxK(coressponses to outer dimentions

In [2]:
import numpy as np 

In [3]:
M1=np.random.randn(4,5)
M2=np.random.randn(4,5)

print(np.matmul(M1,M2))

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 5)

In [5]:
# it works transpose one of them according to rule 
print(np.matmul(M1,M2.T))
print(' ')
print(M1@M2.T)
# lest check their result
print(' ')
print(np.matmul(M1,M2.T)-M1@M2.T)

[[-1.97426321  0.2546246  -1.29985564  2.00772265]
 [ 2.34928908  0.87811196 -0.1780943  -1.79485849]
 [-2.21344713  2.31061817 -1.98668852  2.61388927]
 [-0.22199219 -1.86863447 -0.2919146  -0.05895025]]
 
[[-1.97426321  0.2546246  -1.29985564  2.00772265]
 [ 2.34928908  0.87811196 -0.1780943  -1.79485849]
 [-2.21344713  2.31061817 -1.98668852  2.61388927]
 [-0.22199219 -1.86863447 -0.2919146  -0.05895025]]
 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
